import NavCard from "@/components/common/NavCard";

export const runtime = "edge";

export default function Home() {
  return (
    <main className="prose dark:prose-invert m-auto min-h-screen w-screen max-w-5xl p-12">
      <h1>AI SDK testing suite</h1>
      <ul className="flex flex-col gap-2">
        {ITEMS.map((item) => (
          <NavCard key={item.href} {...item} />
        ))}
      </ul>
    </main>
  );
}

const ITEMS: NavCard[] = [
  {
    title: "AI Text Generation",
    description:
      "Simple example of a component displaying streaming text generated by the AI from a prompt.",
    href: "/text",
  },
  {
    title: "AI Image Generation",
    description:
      "Simple example of a component displaying streaming image generated by the AI from a prompt.",
    href: "/image",
  },
];
